version: 2.1

commands:
  yarninstall:
    steps:
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

jobs:
  build_develop:
    docker:
    - image: circleci/node:10-stretch
    - image: circleci/mongo:3.6
    working_directory: ~/trudesk
    steps:
    - checkout
    - yarninstall
    - run:
        name: Run Tests
        command: yarn run test
    - run:
        name: Run Build
        command: yarn run build
    - run:
        name: Run Codacy
        command: yarn run codacy
  build_production:
    docker:
    - image: circleci/node:10-stretch
    - image: circleci/mongo:3.6
    working_directory: ~/trudesk
    steps:
    - checkout
    - run:
        name: Install npx
        command: sudo npm i -g npx
    - yarninstall
    - run:
        name: Run Tests
        command: yarn run test
    - run:
        name: Run Codacy
        command: yarn run codacy
    - run:
        name: Semantic Release
        command: npx semantic-release

workflows:
  version: 2.1
  develop:
    jobs:
    - build_develop:
        filters:
          branches:
            only: develop
  production:
    jobs:
    - build_production:
        filters:
          branches:
            only: master